faulty_velocity_controller: 
  ros__parameters:
    joints:
      - joint_X
      - joint_Y
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
    open_loop_control: true
    # gains are used only if open_loop_control is set to false
    gains:
      joint_X:
        ff_velocity_scale: 1.0
        p: 0.1
        d: 0.0
        i: 0.0
      joint_Y:
        ff_velocity_scale: 1.0
        p: 0.1
        d: 0.0
        i: 0.0
    default_drift: [-0.2, 0.5]
    clamp:
        position:
            ub: [1.0, 1.0]
            lb: [0.0, 0.0]
        velocity:
            ub: [10.0, 10.0]
            lb: [-10.0, -10.0]